version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test

description: 
  Verifies the Heroku API key has been added so we can authenticate.
parameters:
  print-whoami:
    default: false
    description: 'Print the result of heroku auth:whoami.'
    type: boolean
steps:
  - run:
      command: 
        if [[ $HEROKU_API_KEY == "" ]]; then
          echo "No Heroku API key set, please set the HEROKU_API_KEY environment variable."
          echo "This can be found by running the `heroku auth:token` command locally."
          exit 1
        else
          echo "Heroku API key found."
        fi
      name: Verify HEROKU_API_KEY is set


workflows:
  heroku_deploy:
    environment:
      HEROKU_APP: "applicationiim"
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: npm install
    jobs:
      - build
      - heroku/deploy-via-git:
        requires:
            - build
          filters:
            branches:
              only: main
        parameters:
            api-key:
                default: HEROKU_API_KEY
                type: env_var_name
            app-name:
                default: $HEROKU_APP_NAME
                type: string
            branch:
                default: main
                type: string
            force:
                default: false
                type: boolean
            maintenance-mode:
                default: false
                type: boolean
          